# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DOzlZJcJBo7BWf9GQweJMQb_-jaMAkEp
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns;sns.set()

rng=np.random.RandomState(1)
x=10*rng.rand(50)

y=2*x-5+rng.randn(50)

plt.scatter(x,y)



from ast import literal_eval
from sklearn.linear_model import LinearRegression
model=LinearRegression(fit_intercept=True)

model.fit(x[:,np.newaxis],y)

print("model slope: ",model.coef_[0])
print("model intercept: ",model.intercept_)

